# Generated by Django 5.0.6 on 2024-06-13 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds_price', models.FloatField(verbose_name='Ціна насіння з ПДВ 14%')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс валюти')),
                ('oil_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна олії')),
                ('oil_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Олія доставка, ПДВ 0%')),
                ('dealer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дилер, ПДВ 0%')),
                ('broker', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Брокер, ПДВ 0%')),
                ('oil_batch_weight', models.FloatField(verbose_name='Вага партії олії')),
                ('planned_profit', models.FloatField(verbose_name='Плановий прибуток на 1 тонні олії')),
                ('oil_content_base', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Олійність базова')),
                ('oil_content_working', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Олійність робоча')),
                ('aditional_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доплата за 1% олійності')),
                ('oil_output', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вихід олії')),
                ('makukha_output', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вихід макухи')),
                ('pellet_output', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вихід пелети')),
                ('perfomance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Продуктивність')),
                ('price_makukha_without_bb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна макухи без Біг Біга без ПДВ')),
                ('price_pellets_in_bb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна пелети в Біг Беге без ПДВ')),
                ('vat_agro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ПДВ агро')),
                ('vat_regular', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ПДВ звичайний')),
                ('tax_burden', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Податкове навантаження')),
                ('vat_discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ПДВ дисконт')),
                ('electro_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість електроенергії, з ПДВ 20%')),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Електроенергія')),
                ('oda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ОПР')),
                ('payroll', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ФОТ')),
                ('recycling', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Переробка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
