# Generated by Django 5.0.6 on 2024-06-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropcalculation',
            name='oil_batch_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вага партії олії'),
        ),
        migrations.AlterField(
            model_name='cropcalculation',
            name='planned_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Плановий прибуток на 1 тонні олії'),
        ),
        migrations.AlterField(
            model_name='cropcalculation',
            name='seeds_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна насіння з ПДВ 14%'),
        ),
    ]
