# Generated by Django 5.0.6 on 2024-07-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cropcalculation_recycling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('text', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс')),
            ],
        ),
        migrations.RemoveField(
            model_name='cropcalculation',
            name='rate',
        ),
        migrations.AlterField(
            model_name='cropcalculation',
            name='electricity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Електроенергія кВТ/доба'),
        ),
        migrations.AlterField(
            model_name='cropcalculation',
            name='oda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ЗВВ  грн/т'),
        ),
        migrations.AlterField(
            model_name='cropcalculation',
            name='payroll',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ФОТ грн/доба'),
        ),
    ]
