# Generated by Django 5.0.6 on 2024-07-22 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_currency_remove_cropcalculation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropcalculation',
            name='rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.currency', verbose_name='Курс грн/валюта'),
        ),
    ]
