# Generated by Django 5.0.6 on 2024-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cropcalculation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс'),
        ),
    ]
