# Generated by Django 5.0.6 on 2024-07-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropcalculation',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.currency', verbose_name='Курс грн/валюта'),
            preserve_default=False,
        ),
    ]
